Added Skywater 130 to memakerwrap.py
IObundle/iob-mem pull request #103
Opened 2021-12-10 19:15 UTC by microSharjeel

2021-12-12 16:56 UTC, JDLopes requested changes
Please, read the comments and apply the requested changes.

2021-12-12 16:56 UTC, JDLopes commented on software/python/memakerwrap.py
> +    print "    parameter ADDR_W = 13,"
These values are only default values. Why change them? Every time a memory is instantiated, these parameters are set. Please, revert this.

2021-12-12 16:56 UTC, JDLopes commented on software/python/memakerwrap.py
> +    if (tech == "LD130")or(tech=="skywater130"):
This is the name of the Verilog module that is generated by the tool that generates memories. In the case of umc130 technology is the Memaker tool, in the case of SkyWater technology is the OpenRAM tool. The existing if statement takes care of the Verilog modules' name for the memories generated by Memaker. You should create one similar to this one for the OpenRAM tool.

Since OpenRAM has no fixed names for the generated memories and the user can define the modules' names, I suggest something like this:

{tech}_{type}_{word_size}x{num_words}_{write_size}

ex.: sky130_spram_32x1024_8, for a single-port RAM with one read-write port and one read-only port, with 1024 words of 32bits each, written to the byte level.

I practically copied it from one of the examples in OpenRAM/compiler/example_configs folder. The final name can be discussed, but as you can see, there are no CM, or BM or Xs. They are and should be different from the ones generated by the Memaker tool.


Please, remove the or condition and add your own if statement for OpenRAM tool memories.

2021-12-12 16:56 UTC, JDLopes commented on software/python/memakerwrap.py
> +    elif sys.argv[1] == "skywater130":
There are no references to SZ, or SJ, etc for the OpenRAM memories. So please, re-write this section to treat OpenRAM (or SkyWater) memories' arguments. You can use some common parts for the code, but not as they are for the Memaker memories.

2021-12-12 17:43 UTC, microSharjeel commented
Hi
Ok I will add all these changes and will submit another PR to iob-mem
regards


On Sun, 12 Dec 2021 at 21:56, JDLopes ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please, read the comments and apply the requested changes.
> ------------------------------
>
> In software/python/memakerwrap.py
> <https://github.com/IObundle/iob-mem/pull/103#discussion_r767295404>:
>
> > @@ -28,8 +28,8 @@ def timeScale () :
>  def initModule (moduleName, type, async) :
>      print "module "+moduleName
>      print "  #("
> -    print "    parameter DATA_W = 8,"
> -    print "    parameter ADDR_W = 9,"
> +    print "    parameter DATA_W = 32,"
> +    print "    parameter ADDR_W = 13,"
>
> These values are only default values. Why change them? Every time a memory
> is instantiated, these parameters are set. Please, revert this.
> ------------------------------
>
> In software/python/memakerwrap.py
> <https://github.com/IObundle/iob-mem/pull/103#discussion_r767299951>:
>
> >
>  def instMemory (tech, type, words, bits, bytes, mux):
>      # memory simulation modute name
> -    if tech == "LD130":
> +    if (tech == "LD130")or(tech=="skywater130"):
>
> This is the name of the Verilog module that is generated by the tool that
> generates memories. In the case of umc130 technology is the Memaker tool,
> in the case of SkyWater technology is the OpenRAM tool. The existing if
> statement takes care of the Verilog modules' name for the memories
> generated by Memaker. You should create one similar to this one for the
> OpenRAM tool.
>
> Since OpenRAM has no fixed names for the generated memories and the user
> can define the modules' names, I suggest something like this:
>
> {tech}*{type}*{word_size}x{num_words}_{write_size}
>
> ex.: sky130_spram_32x1024_8, for a single-port RAM with one read-write
> port and one read-only port, with 1024 words of 32bits each, written to the
> byte level.
>
> I practically copied it from one of the examples in
> OpenRAM/compiler/example_configs folder. The final name can be discussed,
> but as you can see, there are no CM, or BM or Xs. They are and should be
> different from the ones generated by the Memaker tool.
>
> Please, remove the or condition and add your own if statement for OpenRAM
> tool memories.
> ------------------------------
>
> In software/python/memakerwrap.py
> <https://github.com/IObundle/iob-mem/pull/103#discussion_r767300369>:
>
> > @@ -389,6 +472,42 @@ def main () :
>                  mems.append([words, bits, mux])
>          else:
>              sys.exit("Unsupported memory type")
> +    elif sys.argv[1] == "skywater130":
>
> There are no references to SZ, or SJ, etc for the OpenRAM memories. So
> please, re-write this section to treat OpenRAM (or SkyWater) memories'
> arguments. You can use some common parts for the code, but not as they are
> for the Memaker memories.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IObundle/iob-mem/pull/103#pullrequestreview-829644820>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQM65EI4SCMU62LGDX6SC3UQTH27ANCNFSM5JZ26XWA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-13 15:56 UTC, microSharjeel commented on software/python/memakerwrap.py
> +    elif sys.argv[1] == "skywater130":
OpenLane only require type SJ and SH

2021-12-13 15:57 UTC, microSharjeel commented on software/python/memakerwrap.py
> +    if (tech == "LD130")or(tech=="skywater130"):
changed accordingly in a new PR that will outdate this PR

2021-12-13 15:57 UTC, microSharjeel commented on software/python/memakerwrap.py
> +    print "    parameter ADDR_W = 13,"
changed in PR that will outdate this one

2021-12-13 17:38 UTC, closed without merging

2021-12-13 17:38 UTC, JDLopes requested changes
Pay attention to indentation for Python scripts. Use your text editor (or IDE if you use one) set correctly, so tabs are not mixed up with spaces. It seems to me that you have one or two lines badly indented.

Please, check the code lines indentation.

2021-12-13 17:38 UTC, JDLopes commented on software/python/memakerwrap.py
> +
I think you missed one thing: the indentation of the ifs, they seem to be with the same indentation. And between tech and type should be an underscore, right?

2021-12-13 17:38 UTC, JDLopes commented on software/python/memakerwrap.py
> +    elif tech == "skywater130":
tech for OpenRAM is sky130, not skywater130, I think.

2021-12-13 17:38 UTC, JDLopes commented on software/python/memakerwrap.py
> +    elif sys.argv[1] == "skywater130":
More or less, you can have ROMs as well (SP), as we discussed earlier.

2021-12-13 17:38 UTC, JDLopes commented on software/python/memakerwrap.py
> +        if sys.argv[3] == "SZ":
These types (SZ, SJ, SH and SP) came from Memaker tool. They don't exist in OpenRAM. I suggest you use spram, dpram, sprom, spregf, etc, as types. Then, for coding reuse, you associate them with the ones used for Memaker: register file (SZ), or dual-port RAM (SJ), or single-port RAM (SH), or single-port ROM (SP), by simply setting the type variable to right one.